dtb-$(CONFIG_ARCH_MESON) += gxl_p212_1g.dtb \
	gxl_p212_1g_buildroot.dtb \
	gxl_p212_1g_hd.dtb \
	gxl_p212_2g.dtb \
	gxl_p212_2g_buildroot.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
