name: Compilar Kernel Amlogic

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04  # Use older Ubuntu version for compatibility

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc rsync git gcc-arm-linux-gnueabihf

      - name: Limpeza do build anterior
        run: |
          make ARCH=arm mrproper

      - name: Configurar o Kernel
        env:
          CONFIG_: CONFIG_
        run: |
          make ARCH=arm meson64_a32_defconfig
          echo "Configurando Bluetooth para USB dongle Broadcom..."
          chmod +x ./scripts/config
          
          # Core Bluetooth support
          ./scripts/config --enable CONFIG_BT
          ./scripts/config --enable CONFIG_BT_LE
          
          # Enable USB HCI driver (required for USB dongles)
          ./scripts/config --module CONFIG_BT_HCIUSB
          
          # Enable Broadcom USB Bluetooth driver as module
          ./scripts/config --module CONFIG_BT_HCIBCM203X
          
          # Disable Realtek USB Bluetooth drivers
          ./scripts/config --disable CONFIG_BT_HCIBTUSB_RTL
          ./scripts/config --disable CONFIG_BT_HCIBTUSB_RTL8723A
          ./scripts/config --disable CONFIG_BT_HCIBTUSB_RTL8821A
          ./scripts/config --disable CONFIG_BT_HCIBTUSB_RTLWCI
          
          # Optional: disable other vendor USB dongle drivers (e.g., Cambridge Silicon Radio, Intel)
          ./scripts/config --disable CONFIG_BT_HCIBPA10
          ./scripts/config --disable CONFIG_BT_HCIBFUSB
          ./scripts/config --disable CONFIG_BT_HCIVHCI
          ./scripts/config --disable CONFIG_BT_HCIUART
          
          # Enable protocol modules typically needed for Bluetooth
          ./scripts/config --module CONFIG_BT_RFCOMM
          ./scripts/config --module CONFIG_BT_RFCOMM_TTY
          ./scripts/config --module CONFIG_BT_BNEP
          ./scripts/config --set-string CONFIG_BT_BNEP_PROTO_FILTER "y"
          ./scripts/config --module CONFIG_BT_HIDP
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- olddefconfig

      - name: Compilar o Kernel, DTBs e módulos
        env:
          CONFIG_: CONFIG_
        run: |
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc)
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=../kernel_output modules_install

      - name: Preparar artefatos
        run: |
          mkdir -p ../kernel_output/dts/
          cp arch/arm/boot/zImage ../kernel_output/
          cp arch/arm/boot/dts/amlogic/meson-gxl-s905x-*.dtb ../kernel_output/dts/
          cp .config ../kernel_output/

      - name: Upload dos Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Amlogic
          path: ../kernel_output/
