name: Compilar Kernel Amlogic

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc rsync git gcc-arm-linux-gnueabihf

      - name: Limpeza do build anterior
        run: |
          make ARCH=arm mrproper

      - name: Configurar o Kernel
        env:
          CONFIG_: CONFIG_
        run: |
          # Use ARMv7-A flags for compatibility with S905X running Android 32-bit
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabihf-
          export CFLAGS="-march=armv7-a"
          export KCFLAGS="-march=armv7-a"

          make ARCH=arm meson64_a32_defconfig
          chmod +x ./scripts/config

          # Core Bluetooth support
          ./scripts/config --enable CONFIG_BT
          ./scripts/config --enable CONFIG_BT_BREDR
          ./scripts/config --enable CONFIG_BT_LE

          # Enable USB HCI driver (main USB Bluetooth driver)
          ./scripts/config --module CONFIG_BT_HCIBTUSB

          # Enable Broadcom USB Bluetooth support
          ./scripts/config --module CONFIG_BT_BCM

          # Enable RFCOMM protocol support
          ./scripts/config --module CONFIG_BT_RFCOMM
          ./scripts/config --enable CONFIG_BT_RFCOMM_TTY

          # Enable BNEP protocol support  
          ./scripts/config --module CONFIG_BT_BNEP
          ./scripts/config --enable CONFIG_BT_BNEP_MC_FILTER
          ./scripts/config --enable CONFIG_BT_BNEP_PROTO_FILTER

          # Enable HIDP protocol support
          ./scripts/config --module CONFIG_BT_HIDP

          # Enable 6LoWPAN support (optional)
          ./scripts/config --module CONFIG_BT_6LOWPAN || true

          # Enable debugging (optional, can be removed for production)
          ./scripts/config --enable CONFIG_BT_SELFTEST || true
          ./scripts/config --enable CONFIG_BT_DEBUGFS || true

          # Enable compatibility mode (important for 32-bit on 64-bit SoCs)
          ./scripts/config --enable CONFIG_COMPAT

          # Disable DVB/Live TV and CA/Descrambler support
          ./scripts/config --disable CONFIG_DVB_CORE
          ./scripts/config --disable CONFIG_DVB_CA
          ./scripts/config --disable CONFIG_DVB
          ./scripts/config --disable CONFIG_DVB_USB
          ./scripts/config --disable CONFIG_DVB_ATSC
          ./scripts/config --disable CONFIG_AMLOGIC_DVB
          ./scripts/config --disable CONFIG_AMLOGIC_DVB_CA
          ./scripts/config --disable CONFIG_AMLOGIC_DVB_DSC

          # Apply configuration
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- olddefconfig

      - name: Compilar o Kernel, DTBs e módulos
        env:
          CONFIG_: CONFIG_
        run: |
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabihf-
          export CFLAGS="-march=armv7-a"
          export KCFLAGS="-march=armv7-a"
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- CFLAGS="-march=armv7-a" KCFLAGS="-march=armv7-a" -j$(nproc)
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=../kernel_output modules_install

      - name: Preparar artefatos
        run: |
          mkdir -p ../kernel_output/dts/
          cp arch/arm/boot/zImage ../kernel_output/
          cp arch/arm/boot/dts/amlogic/meson-gxl-s905x-*.dtb ../kernel_output/dts/
          cp .config ../kernel_output/

      - name: Upload dos Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Amlogic
          path: ../kernel_output/
