name: Compilar Kernel 64bits
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/.github/workflows/build.yml') }}

      - name: Instalar dependências e Toolchain AArch64
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libncurses-dev \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            bc \
            rsync \
            git \
            wget \
            gcc-aarch64-linux-gnu \
            device-tree-compiler \
            lzop \
            u-boot-tools \
            cpio \
            kmod

      - name: Limpar build anterior
        run: |
          make ARCH=arm64 mrproper || true
          rm -rf kernel_output || true

      - name: Configurar o Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export LOCALVERSION="-s905x-a32"

          cp .configatv .config
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig

      - name: Exibir informações da configuração
        run: |
          echo "=== Compilador ==="
          aarch64-linux-gnu-gcc --version

      - name: Compilar o Kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          make -j$(nproc) \
               ARCH=arm64 \
               CROSS_COMPILE=aarch64-linux-gnu- \
               Image.gz 2>&1 | tee build_kernel.log || {
            echo "=== Erro na compilação do kernel ==="
            tail -100 build_kernel.log
            exit 1
          }

      - name: Compilar DTBs
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc) \
               ARCH=arm64 \
               CROSS_COMPILE=aarch64-linux-gnu- \
               dtbs 2>&1 | tee build_dtbs.log || {
            echo "=== Erro na compilação dos DTBs ==="
            tail -100 build_dtbs.log
            exit 1
          }

      - name: Compilar e Instalar Módulos
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc) \
               ARCH=arm64 \
               CROSS_COMPILE=aarch64-linux-gnu- \
               modules 2>&1 | tee build_modules.log || {
            echo "=== Erro na compilação dos módulos ==="
            tail -100 build_modules.log
            exit 1
          }
          mkdir -p kernel_output
          make ARCH=arm64 \
               CROSS_COMPILE=aarch64-linux-gnu- \
               INSTALL_MOD_PATH=kernel_output \
               INSTALL_MOD_STRIP=1 \
               modules_install

          # Limpeza dos diretórios desnecessários
          rm -rf kernel_output/lib/modules/*/build
          rm -rf kernel_output/lib/modules/*/source

      - name: Preparar artefatos
        run: |
          mkdir -p kernel_output/{boot,dtbs,logs}

          if [ -f "arch/arm64/boot/Image.gz" ]; then
            cp arch/arm64/boot/Image.gz kernel_output/boot/
            echo "Image.gz copiado com sucesso"
          else
            echo "ERRO: Image.gz não encontrado!"
            ls -la arch/arm64/boot/
            exit 1
          fi
          
          shopt -s nullglob
          dtbs=(arch/arm64/boot/dts/amlogic/gxl_p212_*.dtb)
          if [ ${#dtbs[@]} -eq 0 ]; then
            echo "ERRO: Nenhum DTB gxl_p212_* encontrado!"
            ls -la arch/arm64/boot/dts/amlogic/
            exit 1
          else
            cp "${dtbs[@]}" kernel_output/dtbs/
            echo "DTBs gxl_p212_* copiados com sucesso"
          fi
          
          cp .config kernel_output/
          cp build_*.log kernel_output/logs/ 2>/dev/null || true
          
          gunzip -k kernel_output/boot/Image.gz
          mkimage -A arm64 -O linux -T kernel -C none \
                  -a 0x01080000 -e 0x01080000 \
                  -n "Linux-$(make kernelversion)" \
                  -d kernel_output/boot/Image \
                  kernel_output/boot/uImage || echo "mkimage falhou (não crítico)"

      - name: Upload dos Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: kernel-s905x-arm64
          path: kernel_output/
